version: '3'

# This is the docker-compose file for the Athena Assessment Module Manager
# The Docker Compose configuration files for the individual modules can be found in their respective folders.

services:
  athena_assessment_module_manager:
    build:
      context: .
      dockerfile: ./assessment_module_manager/Dockerfile
    tty: true
    ports:
      - "8000:8000"